# Generated by Django 2.1.4 on 2018-12-09 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('age10', models.DecimalField(decimal_places=0, max_digits=3)),
                ('age20', models.DecimalField(decimal_places=0, max_digits=3)),
                ('age30', models.DecimalField(decimal_places=0, max_digits=3)),
                ('age40', models.DecimalField(decimal_places=0, max_digits=3)),
                ('age50', models.DecimalField(decimal_places=0, max_digits=3)),
                ('age60', models.DecimalField(decimal_places=0, max_digits=3)),
                ('female', models.DecimalField(decimal_places=0, max_digits=3)),
                ('male', models.DecimalField(decimal_places=0, max_digits=3)),
                ('rating', models.FloatField()),
                ('category', models.DecimalField(decimal_places=0, max_digits=1)),
                ('price', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
        ),
    ]
